# Generated by Django 2.2.4 on 2020-04-17 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_auto_20190426_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogauthor',
            name='author',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='catagory',
        ),
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BlogAuthor',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
