# Generated by Django 3.2.13 on 2022-06-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_auto_20200417_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
