# Generated by Django 3.2.13 on 2022-06-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0029_vod'),
    ]

    operations = [
        migrations.AddField(
            model_name='vod',
            name='describe',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
