# Generated by Django 3.2.13 on 2022-06-06 21:16

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0030_vod_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.DateTimeField(auto_now_add=True)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
