# Generated by Django 3.2.13 on 2022-06-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0031_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='sub_title',
            field=models.CharField(max_length=100),
        ),
    ]
